=== RogerPugaRuiz/RealStageAgency/estatesDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/emptyDTD.dtd to edit this template
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT Estates (Estate+)>
<!ELEMENT Estate (Surface,Price,Addres)>
<!ATTLIST Estate type (House | Premises) "House">
<!ELEMENT Surface (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Addres (Street,Number,Floor,Door)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT Floor (#PCDATA)>
<!ELEMENT Door (#PCDATA)>

=== RogerPugaRuiz/RealStageAgency/estates.xml
<?xml version="1.0"?>
<!DOCTYPE Estates SYSTEM "estatesDTD.dtd">

<Estates>
    <Estate type="House">
        <Surface>144</Surface>
        <Price>20000</Price>
        <Addres>
            <Street>Verge del pilar</Street>
            <Number>3</Number>
            <Floor>2</Floor>
            <Door>4</Door>
        </Addres>
    </Estate>
    <Estate type="Premises">
        <Surface>200</Surface>
        <Price>35000</Price>
        <Addres>
            <Street>Pi Maragall</Street>
            <Number>7</Number>
            <Floor>3</Floor>
            <Door>2</Door>
        </Addres>
    </Estate>
    <Estate type="Premises">
        <Surface>45</Surface>
        <Price>15000</Price>
        <Addres>
            <Street>Sant pius X</Street>
            <Number>2</Number>
            <Floor>1</Floor>
            <Door>1</Door>
        </Addres>
    </Estate>
    
</Estates>
